spring:
  application:
    name: messageQueue-demo
  datasource:
    # 数据文件存储的本地路径，我们SQL组织数据就是把数据存储在我们当前磁盘的一个指定的文件中
    # 当前我们指定的是什么文件作为我们的数据库文件，基准路径就是我们的当前项目所在的路径（在IDEA中）
    url: jdbc:sqlite:./data/meta.db
    # 无需用户与密码
    username:
    password:
    driver-class-name: org.sqlite.JDBC

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true